### ISSUE TITLE
SVG image files are not displayed.

### ISSUE THREAD

**Issue by johnholliday** [kernoeb/docker-docsify-pdf#4]
The following text fails to load the image.  This approach is apparently required for displaying SVG files.

```
### High-Level System Landscape

### Sequence
<img src="_generated/wsd/svg/structurizr-1-Taxonomy.svg" />
```

![PDF generator - Image Files](https://user-images.githubusercontent.com/5294044/186673207-b525ddf7-877c-45f6-b9c5-5ba3a5876751.jpg)

**Comment by kernoeb** [comment]
Why don't use Markdown syntax ?

![image.svg](image.svg)

But you're right, html links should be working, let me check that

**Comment by johnholliday** [comment]
Markdown syntax also fails to load images in docsify:

```
![Sequence Diagram](_generated/wsd/png/structurizr-1-Taxonomy.png)
```
![PDF generator - PNG files](https://user-images.githubusercontent.com/5294044/186678431-1dc90afb-3b0b-4f32-bc29-07a1e3942ce7.jpg)

**Comment by kernoeb** [comment]
Is the path relative to the markdown ? 

I just tried, it works if you use this syntax : `![Rick](../usecase/img.png)` for example

`_generated` is same as `./_generated`

**Comment by johnholliday** [comment]
Silly me! 👍🏾

**Comment by kernoeb** [comment]
I created another branch with something more robust..

https://github.com/kernoeb/docker-docsify-pdf/tree/better-files-handling

But I need to test it on my production environment (I use the latest version in my company !), so I'll try it before merging anything (I'll keep you posted) 👍

**Comment by kernoeb** [comment]
Merged in https://github.com/kernoeb/docker-docsify-pdf/tree/v4.0.0 🎉 

There shouldn't be actual breaking changes, but it's a refactor of how some files are managed
