### ISSUE TITLE
Export a subset of the documentation

### ISSUE THREAD

**Issue by Acwok** [kernoeb/docker-docsify-pdf#6]
Hello,

Is there a way to export only a subset of the documentation ?  
I think it could be interesting to have a file listing which pages to exclude (a `docsify-pdf.ignore` for example)

**Comment by kernoeb** [comment]
Hello,
The current easiest way to do that would be to map a volume on the sidebar.md (there is an example indicated at the bottom of the readme, in the footnote). Just create a temporary sidebar.md file which contains your subset of the doc and the container will read this one instead !

I know that's just a temporary solution, but imo this would be a feature of Docsify, not docker-docsify-pdf (i'm using a Docsify server and _sidebar.md to get the list of files and create the T.O.C : it is just a "copy" of the sidebar)

If you have an idea to implement this a generic way, tell me, I'll be happy to check that :)

**Comment by Acwok** [comment]
Indeed, it's a good solution.
Thanks!
