### ISSUE TITLE
Included files cause blank PDF

### ISSUE THREAD

**Issue by dim59130** [kernoeb/docker-docsify-pdf#8]
Hi,
I have the following line in my markdown file:
`[filename](ressources/diagrams/my_markdown.md ':include')`

- `ressources/diagrams/my_markdown.md` file exist under docs folder
- `docsify serve` command work well
- Site is displayed without issue
- When docker-docsify-pdf is launched the docker to create a blank PDF (juste the cover)
- When i remove the line, the PDF generation is back to normal (no problem)

I followed this documentation:
[https://docsify.js.org/#/embed-files](https://docsify.js.org/#/embed-files)

**Comment by dim59130** [comment]
Sorry issue is already tracked here:
[https://github.com/meff34/docsify-to-pdf-converter/issues/3](https://github.com/meff34/docsify-to-pdf-converter/issues/3)

**Comment by kernoeb** [comment]
Interesting, I even didn't know this is possible with Docsify haha 
I'll check this asap 👍

**Comment by kernoeb** [comment]
@dim59130, can you try with the main version of the docker image ?

I added some examples in the docs directory, it looks to work now, even iframes

Please tell me if it's working, then I will tag a new version 👍

**Comment by dim59130** [comment]
It works, file is now included, thanks
