### ISSUE TITLE
Link in the document are broken in the PDF

### ISSUE THREAD

**Issue by dim59130** [kernoeb/docker-docsify-pdf#9]
Hi,
Another issue i just found

1. On docsify with serve we specify the link for example:
`[My link](/messages?id=test)` to access `#test` title

2. On the pdf i neet to put:
`[My link](#test)` for the link to work

Do you have an idea how i can write this same link on both format ? It is an issue ?

**Comment by kernoeb** [comment]
Is this documented in Docsify documentation ? I could maybe add a special case for internal links with interrogation marks

**Comment by dim59130** [comment]
I can't find anthing about links in the documentation but when we look at the URL displayed in docsify serve, it seem to be the way they choose to handle titles.

**Comment by dim59130** [comment]
Seem to have found a solution
Sorry to have bothered you and many thanks for the active support !

---

[home](/home#here)
[home](/home.md#here)
[home](/home?id=here)

All will be compiled to:
<a  href="/#/home?id=here">home</a>

**Comment by kernoeb** [comment]
Thanks! I'll add this in the docs example
